#!/usr/bin/env bash
###########################################################################
#                                                                         #
#   Copyright (c)                                                         #
#     Arvid Norlander <anmaster@kuonet.org>                               #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
###########################################################################
# Generate list of numerics from the numerics.txt
# Output to STDOUT.
# Run this in main dir.

cat - << EOF
#!/bin/bash
###########################################################################
#                                                                         #
#   Copyright (c)                                                         #
#     Arvid Norlander <anmaster@kuonet.org>                               #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
###########################################################################

###########################################################################
#                                                                         #
# WARNING THIS FILE IS AUTOGENERATED. ANY CHANGES WILL BE OVERWRITTEN!    #
# See the source in tools/numerics.txt for comments about some numerics   #
# This file was generated with tools/build_numerics.sh                    #
#                                                                         #
###########################################################################

# This file contains a list of numerics that we currently use.
# It is therefore incomplete.

##########################
# Name -> number mapping #
##########################

# During connect, these are sent. They are NOT part of RFC 1459.
# For some format of the parameters varies between servers.
numeric_RPL_WELCOME='001'  # "Welcome to <network>"
numeric_RPL_YOURHOST='002' # "Your host is <servername>, running version <ver>"
numeric_RPL_MYINFO='004'   # "<servername> <version> <available user modes> <available channel modes>"
numeric_RPL_ISUPPORT='005' # Not in any RFC. See http://www.irc.org/tech_docs/005.html for incomplete list.

# "Normal" numerics.
EOF
# The numerics above are special case, otherwise bash strips leading 0.

# Yes a bash file with .txt..
source tools/numerics.txt || { echo 'Failed to source.' >&2; exit 1; }

for index in ${!numeric[*]}; do
	echo "numeric_${numeric[$index]}='$index'"
done

# Same special case as above.
cat - << EOF

##########################
# Number -> name mapping #
##########################

# During connect, these are sent. They are NOT part of RFC 1459.
# For some format of the parameters varies between servers.
numeric[001]='RPL_WELCOME'  # "Welcome to <network>"
numeric[002]='RPL_YOURHOST' # "Your host is <servername>, running version <ver>"
numeric[004]='RPL_MYINFO'   # "<servername> <version> <available user modes> <available channel modes>"
numeric[005]='RPL_ISUPPORT' # Not in any RFC. See http://www.irc.org/tech_docs/005.html for incomplete list.

# "Normal" numerics.
EOF
for index in ${!numeric[*]}; do
	echo "numeric[$index]='${numeric[$index]}'"
done

cat - << EOF

# End of generated file.
EOF
